application: checkit-flask-test
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "10m"

# env_variables:
  # NAME: 'string'

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on
- appstats: on

# libraries:
# - name: name
#   version: latest

handlers:

- url: /static
  static_dir: static
  secure: optional

- url: /.*
  script: main.app
